<div class="row box">
        <div class="full-width content-40">
            <img src="images/group/<?= $group['group_img']?>" alt="">
        </div>
        <div class="col btw box content-60">
            <h2><?= htmlspecialchars($group['group_title'])?></h2>
            <p><?= htmlspecialchars($group['group_description'])?></p>
        </div>
    </div>
    <div class="grp-menu">
        <nav>
            <ul>
                <?php if($_SESSION['user']['group_id'] == $group['group_id']):?>
                    <li><a href="?page=Articles/Add&group_id=<?= $group['group_id']?>" title="Créer un Article">Créer Article</a></li>
                <?php endif;?>
                <?php if($_SESSION['user']['group_id'] != $group['group_id']):?>
                    <li><a href="?page=Group&group_id=<?= $group['group_id']?>&join=1" title="Rejoindre le groupe">Rejoindre le groupe!</a></li>
                <?php endif;?>
            </ul>
        </nav>
    </div>