<main class="container box-shd">

    <?php include'views/Group/MenuGroup.phtml' ;?>

    <section>
        <h2>Créer un Article</h2>
        <div id="create_form">
            <form action="?page=Articles/Add&group_id=<?= $group['group_id']?>" method="POST">
                <label for="article_title"><h2>Titre de l'article</h2></label>
                    <input type="text" name="article_title" id="article_title">
                <label for="jeu_name">Associer un jeu</label>
                    <select name="jeu_name" id="jeu_name">
                        <?php foreach($jeux as $jeu):?>
                            <option value="<?= $jeu['jeu_id']?>"><?= $jeu['jeu_title']?></option>
                        <?php endforeach;?>
                    </select>
                <label for="visible_by">visibilité</label>
                    <select name="visible_by" id="visible_by">
                        <option value="0">Personne à par moi</option>
                        <option value="1">Membres du Groupe</option>
                        <option value="2" selected>Tout le monde</option>
                    </select>
                <label for="article_content"><h2>Écrivez votre Article !</h2></label>
                    <textarea name="article_content" id="article_content" rows="5" cols="60"></textarea>
                    <input type="submit" value="Envoyez votre article !">
            </form>
            <a href="?page=Group&group_id=<?= $group['group_id']?>">ANNULER</a>
            <hr>
        </div>
    </section>
</main>
